Repository APSIMInitiative/ApsimX, pull requests merged in 2025-09, with the labels that each got.

#10401 Fixed layer reference to get clover working. Put clover and ryegrass …
  Models/Pasture/grazpastpopn.cs
  Models/Pasture/pasture.cs
  Prototypes/Pasture/AusFarmClover.xlsx
  Prototypes/Pasture/AusFarmPerennialRyegrass.csv
  Prototypes/Pasture/AusFarmPerennialRyegrassOutputs.csv
  Prototypes/Pasture/Clover/Clover.apsimx
  Prototypes/Pasture/Hamilton.txt
  Prototypes/Pasture/Pasture.apsimx
  Prototypes/Pasture/PerennialRyegrass/ausfarm-resource.txt
  Prototypes/Pasture/PerennialRyegrass/log-apsim.txt
  Prototypes/Pasture/PerennialRyegrass/log-ausfarm.txt
Labels: Ready for Software Review

#10453 Dewonkyify soil models that don't have thickness specified
  ApsimNG/Presenters/ProfilePresenter.cs
  Models/Soils/SoilStandardise.cs
  Tests/UnitTests/Soils/SoilStandardiserTests.cs
Labels: Ready for Software Review

#10470 10469 Check model children types if searching by name fails
  APSIM.Core/Locate/Locator.cs
  Tests/UnitTests/APSIM.Core/LocatorTests.cs
Labels: Ready for Software Review

#10474 10471 Locator finds model with brackets
  APSIM.Core/Locate/Locator.cs
  Tests/UnitTests/APSIM.Core/LocatorTests.cs
Labels: Ready for Software Review

#10482 Guard against "physical" being null
  ApsimNG/Presenters/ProfilePresenter.cs
Labels: Ready for Software Review

#10253 Maize Waterlogged Data
  Models/Resources/Maize.json
  Tests/Validation/Maize/Harbin2017-2018.met
  Tests/Validation/Maize/Kaur.met
  Tests/Validation/Maize/Maize.apsimx
  Tests/Validation/Maize/Observations/MaizeObservations.xlsx
Labels: Science, Ready for Reference Panel Review, Ready for Software Review

#10505 10504 Add link to CAMP documentation to Wheat Docs
  APSIM.Documentation/Models/Types/DocSimulations.cs
  Models/Resources/Wheat.json
Labels: Ready for Software Review

#10518 CLEM ensure milking activity happens during the milking event
  Models/CLEM/Activities/RuminantActivityMilking.cs
Labels: Ready for Software Review, Low Level Review

#10524 Removes the string [bot] from the author string
  .github/workflows/run-model-validations.yml
Labels: Ready for Software Review

#10537 10535 Fix creation of Checkpoints
  Models/Factorial/Factor.cs
  Tests/UnitTests/Factorial/FactorTests.cs
Labels: Ready for Software Review, Low Level Review

#10506 Remove IsChildAllowable from IModel and Model.
  Models/Core/Apsim.cs
  Models/Core/IModel.cs
  Models/Core/Model.cs
  Models/Core/Structure.cs
  Tests/UnitTests/APSIM.Core/ApsimFile/StructureTests.cs
  Tests/UnitTests/APSIM.Core/ModelTests.cs
  Tests/UnitTests/SummaryTests.cs
Labels: Ready for Software Review

#10555 10547 FrostHeatDamageFunctions crop name fix
  Models/Functions/FrostHeatDamageFunctions.cs
  Tests/UnitTests/Functions/FrostHeatDamageFunctionsTests.cs
Labels: Ready for Software Review, Low Level Review
